# Converting masked-based implementation to cropping-based implementation

In [0]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import math

In [0]:
test_ones_2d = np.ones([1, 5, 5, 1], dtype='float32')
test_ones_3d = np.ones([1, 5, 5, 5, 1], dtype='float32')

In [0]:
def print_3d(matrix_3d):
    for i in range(matrix_3d.shape[0]):
        print(f'Depth {i}')
        print(matrix_3d[i,...])

In [0]:
print_3d(test_ones_3d.squeeze())

Depth 0
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Depth 1
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Depth 2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Depth 3
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Depth 4
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [0]:
print(test_ones_2d[0,:,:,0].squeeze())

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Creating 2D masked solution to check results with cropped solution later

In [0]:
class MaskedConv2D(tf.keras.layers.Layer):
    def __init__(self,
                 mask_type,
                 filters,
                 kernel_size,
                 strides=1,
                 padding='same',
                 kernel_initializer='glorot_uniform',
                 bias_initializer='zeros'):
        super(MaskedConv2D, self).__init__()

        assert mask_type in {'A', 'B', 'V'}
        self.mask_type = mask_type

        self.filters = filters

        if isinstance(kernel_size, int):
            kernel_size = (kernel_size, kernel_size)
        self.kernel_size = kernel_size

        self.strides = strides
        self.padding = padding.upper()
        self.kernel_initializer = tf.keras.initializers.get(kernel_initializer)
        self.bias_initializer = tf.keras.initializers.get(bias_initializer)

    def build(self, input_shape):
        kernel_h, kernel_w = self.kernel_size

        self.kernel = self.add_weight("kernel",
                                      shape=(kernel_h,
                                             kernel_w,
                                             int(input_shape[-1]),
                                             self.filters),
                                      initializer=self.kernel_initializer,
                                      trainable=True)

        self.bias = self.add_weight("bias",
                                    shape=(self.filters,),
                                    initializer=self.bias_initializer,
                                    trainable=True)

        mask = np.ones(self.kernel.shape, dtype=np.float32)

        if kernel_h % 2 != 0: 
            center_h = kernel_h // 2
        else:
            center_h = (kernel_h - 1) // 2

        if kernel_w % 2 != 0: 
            center_w = kernel_w // 2
        else:
            center_w = (kernel_w - 1) // 2

        if self.mask_type == 'V':
            mask[center_h + 1:, :, :, :] = 0.
        else:
            mask[:center_h, :, :] = 0.
            mask[center_h, center_w + (self.mask_type == 'B'):, :, :] = 0.
            mask[center_h + 1:, :, :] = 0.

        self.mask = tf.constant(mask, dtype=tf.float32, name='mask')

    def call(self, input):
        masked_kernel = tf.math.multiply(self.mask, self.kernel)
        x = tf.nn.conv2d(input, masked_kernel, strides=[1, self.strides, self.strides, 1], padding=self.padding)
        x = tf.nn.bias_add(x, self.bias)
        return x

### Tests with kernel_size 3

#### Vertical stack

In [0]:
mask_type = 'V'
kernel_size=(3, 3)

conv = MaskedConv2D(mask_type=mask_type,
                filters=1,
                kernel_size=kernel_size, 
                padding='same',
                kernel_initializer='ones', 
                bias_initializer='zeros')

result_v = conv(test_ones_2d)

print('MASK')
print(conv.mask.numpy().squeeze())
print('')
print('OUTPUT')
print(result_v.numpy().squeeze())

MASK
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]]

OUTPUT
[[2. 3. 3. 3. 2.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]]


#### Feeding horizontal

In [0]:
padding = keras.layers.ZeroPadding2D(padding=((1,0),0))
cropping = keras.layers.Cropping2D(cropping=((0, 1), 0))

x = padding(result_v)
result = cropping(x)

print('OUTPUT')
print(result.numpy().squeeze())

OUTPUT
[[0. 0. 0. 0. 0.]
 [2. 3. 3. 3. 2.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]]


#### Horizontal stack A

In [0]:
mask_type = 'A'
kernel_size=(3, 3)

conv = MaskedConv2D(mask_type=mask_type,
                filters=1,
                kernel_size=kernel_size, 
                padding='same',
                kernel_initializer='ones', 
                bias_initializer='zeros')

result = conv(test_ones_2d)

print('MASK')
print(conv.mask.numpy().squeeze())
print('')
print('OUTPUT')
print(result.numpy().squeeze())

MASK
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]

OUTPUT
[[0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]]


#### Horizontal stack B

In [0]:
mask_type = 'B'
kernel_size=(3, 3)

conv = MaskedConv2D(mask_type=mask_type,
                filters=1,
                kernel_size=kernel_size, 
                padding='same',
                kernel_initializer='ones', 
                bias_initializer='zeros')

result = conv(test_ones_2d)

print('MASK')
print(conv.mask.numpy().squeeze())
print('')
print('OUTPUT')
print(result.numpy().squeeze())

MASK
[[0. 0. 0.]
 [1. 1. 0.]
 [0. 0. 0.]]

OUTPUT
[[1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]]


### Tests with kernel_size 4

#### Vertical stack

In [0]:
mask_type = 'V'
kernel_size=(4, 4)

padding = keras.layers.ZeroPadding2D(padding=((1,0),0))

conv = MaskedConv2D(mask_type=mask_type,
                filters=1,
                kernel_size=kernel_size, 
                padding='same',
                kernel_initializer='ones', 
                bias_initializer='zeros')

cropping = keras.layers.Cropping2D(cropping=((0, 1), 0))

x = padding(test_ones_2d)
x = conv(x)
result = cropping(x)

print('MASK')
print(conv.mask.numpy().squeeze())
print('')
print('OUTPUT')
print(result.numpy().squeeze())

MASK
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT
[[0. 0. 0. 0. 0.]
 [3. 4. 4. 3. 2.]
 [6. 8. 8. 6. 4.]
 [6. 8. 8. 6. 4.]
 [6. 8. 8. 6. 4.]]


#### Horizontal stack A

In [0]:
mask_type = 'A'
kernel_size=(4, 4)

conv = MaskedConv2D(mask_type=mask_type,
                filters=1,
                kernel_size=kernel_size, 
                padding='same',
                kernel_initializer='ones', 
                bias_initializer='zeros')

result = conv(test_ones_2d)

print('MASK')
print(conv.mask.numpy().squeeze())
print('')
print('OUTPUT')
print(result.numpy().squeeze())

MASK
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT
[[0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]]


#### Horizontal stack B

In [0]:
mask_type = 'B'
kernel_size=(4, 4)

conv = MaskedConv2D(mask_type=mask_type,
                filters=1,
                kernel_size=kernel_size, 
                padding='same',
                kernel_initializer='ones', 
                bias_initializer='zeros')

result = conv(test_ones_2d)

print('MASK')
print(conv.mask.numpy().squeeze())
print('')
print('OUTPUT')
print(result.numpy().squeeze())

MASK
[[0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

OUTPUT
[[1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]]


## Creating 2D cropped solution

In [0]:
class VerticalCroppedConv2d(tf.keras.Model):
    def __init__(self,
                 filters,
                 kernel_size,
                 kernel_initializer, 
                 bias_initializer):
        super(VerticalCroppedConv2d, self).__init__(name='')

        if isinstance(kernel_size, int):
            kernel_size = (kernel_size, kernel_size)

        kernel_h, kernel_w = kernel_size

        self.padding = keras.layers.ZeroPadding2D(padding=((kernel_h-1, 0),(int((kernel_w-1)/2),int((kernel_w-1)/2))))

        self.conv = keras.layers.Conv2D(filters=filters,
                                        kernel_size=kernel_size,
                                        strides=1,
                                        padding='valid',
                                        kernel_initializer=kernel_initializer, 
                                        bias_initializer=bias_initializer)

    def call(self, input_value):

        x = self.padding(input_value)
        x = self.conv(x)
        out = self.cropping(x)

        return out



Example step by step

In [0]:
kernel_h = 2
kernel_w = 3

kernel_size = (kernel_h, kernel_w)

padding = keras.layers.ZeroPadding2D(padding=((kernel_h-1, 0),(int((kernel_w-1)/2),int((kernel_w-1)/2))))

res = padding(test_ones_2d)
print(res.numpy().squeeze())

conv = keras.layers.Conv2D(filters=1,
                                        kernel_size=kernel_size,
                                        strides=1,
                                        padding='valid',
                                        kernel_initializer='ones', 
                                        bias_initializer='zeros')

res2 = conv(res)
print(res2.numpy().squeeze())





[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]]
[[2. 3. 3. 3. 2.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]]


In [0]:
conv.weights[0].numpy().squeeze()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [0]:
def build_test_croppedv_stack_2d(input_shape=(5, 5, 1), kernel_size=3):
  inputs = tf.keras.layers.Input(shape=input_shape)
  
  x = VerticalCroppedConv2d(
                   filters=1,
                   kernel_size=kernel_size, 
                   kernel_initializer='ones', 
                   bias_initializer='zeros')(inputs)

  stack = tf.keras.Model(inputs=inputs, outputs=x)
  stack.compile(optimizer='adam', loss='mse')
  return stack

###Tests with kernel_size 3

#### Vertical stack

In [0]:
kernel_size=(2, 3)
kernel_h, kernel_w = kernel_size

padding2 = keras.layers.ZeroPadding2D(padding=((kernel_h-1, 0),(int((kernel_w-1)/2),int((kernel_w-1)/2))))
conv = keras.layers.Conv2D(filters=1,
                           kernel_size=kernel_size,
                           strides=1,
                           padding='valid',
                           kernel_initializer='ones', 
                           bias_initializer='zeros')

x = padding2(test_ones_2d)
result_v = conv(x)

print('KERNEL')
print(conv.weights[0].numpy().squeeze())
print('')
print('OUTPUT')
print(result_v.numpy().squeeze())

KERNEL
[[1. 1. 1.]
 [1. 1. 1.]]

OUTPUT
[[2. 3. 3. 3. 2.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]]


#### Feeding horizontal

In [0]:
padding = keras.layers.ZeroPadding2D(padding=((1,0),0))
cropping = keras.layers.Cropping2D(cropping=((0, 1), 0))

x = padding(result_v)
result = cropping(x)

print('OUTPUT')
print(result.numpy().squeeze())

OUTPUT
[[0. 0. 0. 0. 0.]
 [2. 3. 3. 3. 2.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]
 [4. 6. 6. 6. 4.]]


#### Horizontal stack A

In [0]:
kernel_size=(1, 1)
kernel_h, kernel_w = kernel_size

conv = keras.layers.Conv2D(filters=1,
                           kernel_size=kernel_size,
                           strides=1,
                           kernel_initializer='ones', 
                           bias_initializer='zeros')

padding = keras.layers.ZeroPadding2D(padding=(0,(1,0)))
cropping = keras.layers.Cropping2D(cropping=(0, (0, 1)))

x = conv(test_ones_2d)
x = padding(x)
result = cropping(x)

print('KERNEL')
print(conv.weights[0].numpy().squeeze())
print('')
print('OUTPUT')
print(result.numpy().squeeze())

KERNEL
1.0

OUTPUT
[[0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]]


#### Horizontal stack B

In [0]:
kernel_size=(1, 2)
kernel_h, kernel_w = kernel_size

padding2 = keras.layers.ZeroPadding2D(padding=((int((kernel_h-1)/2),int((kernel_h-1)/2)), (kernel_w-1, 0)))
conv = keras.layers.Conv2D(filters=1,
                           kernel_size=kernel_size,
                           strides=1,
                           padding='valid',
                           kernel_initializer='ones', 
                           bias_initializer='zeros')


x = padding2(test_ones_2d)
result = conv(x)

print('KERNEL')
print(conv.weights[0].numpy().squeeze())
print('')
print('OUTPUT')
print(result.numpy().squeeze())

KERNEL
[1. 1.]

OUTPUT
[[1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2.]]


REFERENCES

https://wiki.math.uwaterloo.ca/statwiki/index.php?title=STAT946F17/Conditional_Image_Generation_with_PixelCNN_Decoders#Gated_PixelCNN

https://www.slideshare.net/suga93/conditional-image-generation-with-pixelcnn-decoders

https://www.youtube.com/watch?v=1BURwCCYNEI